print ("hello" + " " + "world")
print ("foo" + "bar" == "foobar")
print ("10 corgis" != "10" + "corgis")
print ("5" + "5")
print (True + False)
print (1 == 1.0)
print (2 == 1.0)
print (True or False)
print (False or True)